// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRvaKUKpuYxckyxLluk28HlakOSy28DTs',
    appId: '1:675866516912:web:806a026331576fcb69ca75',
    messagingSenderId: '675866516912',
    projectId: 'smart-garbage-collection-app',
    authDomain: 'smart-garbage-collection-app.firebaseapp.com',
    storageBucket: 'smart-garbage-collection-app.firebasestorage.app',
    measurementId: 'G-GBXT4JWLDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASQsJFV7EZfqnGvTXc2_rUFruY5ppiT2A',
    appId: '1:675866516912:android:91513b8180cf4efd69ca75',
    messagingSenderId: '675866516912',
    projectId: 'smart-garbage-collection-app',
    storageBucket: 'smart-garbage-collection-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALtx7wVZTO5RdlPeI66HAUEs3yDVRs5E0',
    appId: '1:675866516912:ios:ab6f4b03fe28fa3869ca75',
    messagingSenderId: '675866516912',
    projectId: 'smart-garbage-collection-app',
    storageBucket: 'smart-garbage-collection-app.firebasestorage.app',
    iosBundleId: 'com.example.smartCityGarabageCollectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALtx7wVZTO5RdlPeI66HAUEs3yDVRs5E0',
    appId: '1:675866516912:ios:ab6f4b03fe28fa3869ca75',
    messagingSenderId: '675866516912',
    projectId: 'smart-garbage-collection-app',
    storageBucket: 'smart-garbage-collection-app.firebasestorage.app',
    iosBundleId: 'com.example.smartCityGarabageCollectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRvaKUKpuYxckyxLluk28HlakOSy28DTs',
    appId: '1:675866516912:web:b65dd4967703ee4569ca75',
    messagingSenderId: '675866516912',
    projectId: 'smart-garbage-collection-app',
    authDomain: 'smart-garbage-collection-app.firebaseapp.com',
    storageBucket: 'smart-garbage-collection-app.firebasestorage.app',
    measurementId: 'G-NCV2FCXHFY',
  );
}
